name: Daily Gold Price

on:
  schedule:
    - cron: '0 8 * * *'  # 每天北京时间8点（UTC时间0点）运行

jobs:
  fetch-gold-price:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python dailygoldprice.py
      env:
        WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}  # 使用GitHub Secrets来存储Webhook URL
